/*****************************************************************************
 * File generated by HDevelop Version 19.05
 *
 * Do not modify!
 *****************************************************************************/

#ifndef HDEV_SEGMENT_PRINTER_CHIP_H
#define HDEV_SEGMENT_PRINTER_CHIP_H

#ifndef __APPLE__
  #include <halconcpp/HalconCpp.h>
#else
  #include <HALCONCpp/HalconCpp.h>
#endif

namespace hdev_segment_printer_chip {

/*****************************************************************************
 * SetResourcePath
 *****************************************************************************
 * Use SetResourcePath in your application to specify the location of the 
 * HDevelop script or procedure library.
 *****************************************************************************/
  void SetResourcePath(const char* resource_path);
#ifdef _WIN32
  void SetResourcePath(const wchar_t* resource_path);
#endif

  void get_printer_chip_region(
    HalconCpp::HObject const& Image,
    HalconCpp::HObject* ConnectedRegions,
    HalconCpp::HTuple const& MinGray);


  void get_printer_chip_regions(
    HalconCpp::HObject const& Image,
    HalconCpp::HObject* ConnectedRegions,
    HalconCpp::HTuple const& MinGray);


  void threshold_printer_chip(
    HalconCpp::HObject const& Image,
    HalconCpp::HObject* Region,
    HalconCpp::HTuple const& MinGray);


    
};

#endif